name: free_trade_zone
channels:
  - defaults
dependencies:
  - python=3.11
  - black
  - flake8
  - hypothesis
  - matplotlib
  - mypy
  - networkx
  - numpy
  - pandas
  - pytest
  - pyyaml
  - recommonmark
  - typing
  - wheel
  - openpyxl
  - lark
  - ipykernel
